name: Weekly Expense Tracker

on:
  schedule:
    - cron: '0 9 * * 1'
  workflow_dispatch:

jobs:
  run-expense-tracker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Debug SERVICE_ACCOUNT_FILE secret
        env:
          SERVICE_ACCOUNT_FILE_SECRET: ${{ secrets.SERVICE_ACCOUNT_FILE }}
        run: |
          if [ -z "$SERVICE_ACCOUNT_FILE_SECRET" ]; then
            echo "SERVICE_ACCOUNT_FILE secret is empty!"
            exit 1
          else
            echo "SERVICE_ACCOUNT_FILE length: ${#SERVICE_ACCOUNT_FILE_SECRET}"
            echo "First 20 chars: ${SERVICE_ACCOUNT_FILE_SECRET}"
          fi

      - name: Create JSON files from secrets
        env:
          SERVICE_ACCOUNT_FILE_SECRET: ${{ secrets.SERVICE_ACCOUNT_FILE }}
          SHEETS_SAC_JSON_SECRET: ${{ secrets.SHEETS_SAC_FILE }}
        run: |
          # Use printf to safely write secret contents to files (avoids heredoc indentation issues)
          printf '%s' "$SERVICE_ACCOUNT_FILE_SECRET" > service_account.json
          printf '%s' "$SHEETS_SAC_FILE_SECRET" > sheets_sac.json
          # Ensure files were created
          ls -l service_account.json sheets_sac.json

      - name: Run Expense Tracker Script
        run: python main.py
