name: Weekly Expense Tracker

# Trigger weekly on Monday at 9 AM UTC, and allow manual trigger
on:
  schedule:
    - cron: '0 9 * * 1'  # Every Monday 9:00 UTC
  workflow_dispatch:      # Manual trigger option

jobs:
  run-expense-tracker:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repo
        uses: actions/checkout@v3

      # Step 2: Setup Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Write JSON secrets to files
      - name: Create JSON files from secrets
        run: |
          echo "${{ secrets.SERVICE_ACCOUNT_JSON }}" > service_account.json
          echo "${{ secrets.SHEETS_SAC_FILE }}" > sheets_sac.json

      # Step 5: Run your expense tracker
      - name: Run Expense Tracker Script
        run: python main.py
        env:
          SERVICE_ACCOUNT_FILE: service_token.json
          SHEETS_SAC_FILE: sac.json
